# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\yacin\Desktop\Python\JDR Tool\ui\client_0.1.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(513, 251)
        MainWindow.setStatusTip("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/icon/13.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ip_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.ip_lineEdit.setGeometry(QtCore.QRect(280, 10, 111, 20))
        self.ip_lineEdit.setObjectName("ip_lineEdit")
        self.port_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.port_lineEdit.setGeometry(QtCore.QRect(430, 10, 61, 20))
        self.port_lineEdit.setObjectName("port_lineEdit")
        self.ip_label = QtWidgets.QLabel(self.centralwidget)
        self.ip_label.setGeometry(QtCore.QRect(260, 10, 16, 16))
        self.ip_label.setObjectName("ip_label")
        self.port_label = QtWidgets.QLabel(self.centralwidget)
        self.port_label.setGeometry(QtCore.QRect(400, 10, 31, 16))
        self.port_label.setObjectName("port_label")
        self.connect_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.connect_pushButton.setGeometry(QtCore.QRect(280, 40, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.connect_pushButton.setFont(font)
        self.connect_pushButton.setObjectName("connect_pushButton")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 40, 251, 181))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(10, 20, 237, 158))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.simple_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.simple_label.setFont(font)
        self.simple_label.setObjectName("simple_label")
        self.gridLayout.addWidget(self.simple_label, 0, 1, 1, 1)
        self.double_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.double_label.setFont(font)
        self.double_label.setObjectName("double_label")
        self.gridLayout.addWidget(self.double_label, 0, 2, 1, 1)
        self.triple_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.triple_label.setFont(font)
        self.triple_label.setObjectName("triple_label")
        self.gridLayout.addWidget(self.triple_label, 0, 3, 1, 1)
        self.eau_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.eau_label.setFont(font)
        self.eau_label.setObjectName("eau_label")
        self.gridLayout.addWidget(self.eau_label, 3, 0, 1, 1)
        self.eau1_spinBox = QtWidgets.QSpinBox(self.widget)
        self.eau1_spinBox.setObjectName("eau1_spinBox")
        self.gridLayout.addWidget(self.eau1_spinBox, 3, 1, 1, 1)
        self.eau2_spinBox = QtWidgets.QSpinBox(self.widget)
        self.eau2_spinBox.setObjectName("eau2_spinBox")
        self.gridLayout.addWidget(self.eau2_spinBox, 3, 2, 1, 1)
        self.eau3_spinBox = QtWidgets.QSpinBox(self.widget)
        self.eau3_spinBox.setObjectName("eau3_spinBox")
        self.gridLayout.addWidget(self.eau3_spinBox, 3, 3, 1, 1)
        self.feu_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.feu_label.setFont(font)
        self.feu_label.setObjectName("feu_label")
        self.gridLayout.addWidget(self.feu_label, 2, 0, 1, 1)
        self.feu1_spinBox = QtWidgets.QSpinBox(self.widget)
        self.feu1_spinBox.setObjectName("feu1_spinBox")
        self.gridLayout.addWidget(self.feu1_spinBox, 2, 1, 1, 1)
        self.feu2_spinBox = QtWidgets.QSpinBox(self.widget)
        self.feu2_spinBox.setObjectName("feu2_spinBox")
        self.gridLayout.addWidget(self.feu2_spinBox, 2, 2, 1, 1)
        self.feu3_spinBox = QtWidgets.QSpinBox(self.widget)
        self.feu3_spinBox.setObjectName("feu3_spinBox")
        self.gridLayout.addWidget(self.feu3_spinBox, 2, 3, 1, 1)
        self.air_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.air_label.setFont(font)
        self.air_label.setObjectName("air_label")
        self.gridLayout.addWidget(self.air_label, 4, 0, 1, 1)
        self.air1_spinBox = QtWidgets.QSpinBox(self.widget)
        self.air1_spinBox.setObjectName("air1_spinBox")
        self.gridLayout.addWidget(self.air1_spinBox, 4, 1, 1, 1)
        self.air2_spinBox = QtWidgets.QSpinBox(self.widget)
        self.air2_spinBox.setObjectName("air2_spinBox")
        self.gridLayout.addWidget(self.air2_spinBox, 4, 2, 1, 1)
        self.air3_spinBox = QtWidgets.QSpinBox(self.widget)
        self.air3_spinBox.setObjectName("air3_spinBox")
        self.gridLayout.addWidget(self.air3_spinBox, 4, 3, 1, 1)
        self.chaos_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chaos_label.setFont(font)
        self.chaos_label.setObjectName("chaos_label")
        self.gridLayout.addWidget(self.chaos_label, 5, 0, 1, 1)
        self.chaos1_spinBox = QtWidgets.QSpinBox(self.widget)
        self.chaos1_spinBox.setObjectName("chaos1_spinBox")
        self.gridLayout.addWidget(self.chaos1_spinBox, 5, 1, 1, 1)
        self.arcane_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.arcane_label.setFont(font)
        self.arcane_label.setObjectName("arcane_label")
        self.gridLayout.addWidget(self.arcane_label, 1, 0, 1, 1)
        self.arcane1_spinBox = QtWidgets.QSpinBox(self.widget)
        self.arcane1_spinBox.setObjectName("arcane1_spinBox")
        self.gridLayout.addWidget(self.arcane1_spinBox, 1, 1, 1, 1)
        self.arcane2_spinBox = QtWidgets.QSpinBox(self.widget)
        self.arcane2_spinBox.setObjectName("arcane2_spinBox")
        self.gridLayout.addWidget(self.arcane2_spinBox, 1, 2, 1, 1)
        self.arcane3_spinBox = QtWidgets.QSpinBox(self.widget)
        self.arcane3_spinBox.setObjectName("arcane3_spinBox")
        self.gridLayout.addWidget(self.arcane3_spinBox, 1, 3, 1, 1)
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(270, 90, 231, 121))
        self.listView.setObjectName("listView")
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(10, 10, 214, 22))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name_label = QtWidgets.QLabel(self.widget1)
        self.name_label.setObjectName("name_label")
        self.horizontalLayout.addWidget(self.name_label)
        self.name_lineEdit = QtWidgets.QLineEdit(self.widget1)
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.horizontalLayout.addWidget(self.name_lineEdit)
        self.deck_checkBox = QtWidgets.QCheckBox(self.widget1)
        self.deck_checkBox.setObjectName("deck_checkBox")
        self.horizontalLayout.addWidget(self.deck_checkBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.case = [self.arcane1_spinBox, self.arcane2_spinBox, self.arcane3_spinBox,
        self.feu1_spinBox, self.feu2_spinBox, self.feu3_spinBox,
        self.eau1_spinBox, self.eau2_spinBox, self.eau3_spinBox,
        self.air1_spinBox, self.air2_spinBox, self.air3_spinBox,
        self.chaos1_spinBox]

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "JDR 13 - client"))
        self.ip_label.setText(_translate("MainWindow", "IP"))
        self.port_label.setText(_translate("MainWindow", "Port"))
        self.connect_pushButton.setText(_translate("MainWindow", "Connexion"))
        self.groupBox.setTitle(_translate("MainWindow", "Composition du deck (total max : 20)"))
        self.simple_label.setText(_translate("MainWindow", "Simple"))
        self.double_label.setText(_translate("MainWindow", "Double"))
        self.triple_label.setText(_translate("MainWindow", "Triple"))
        self.eau_label.setText(_translate("MainWindow", "Eau"))
        self.feu_label.setText(_translate("MainWindow", "Feu"))
        self.air_label.setText(_translate("MainWindow", "Air"))
        self.chaos_label.setText(_translate("MainWindow", "Chaos"))
        self.arcane_label.setText(_translate("MainWindow", "Arcane"))
        self.name_label.setText(_translate("MainWindow", "Nom"))
        self.deck_checkBox.setText(_translate("MainWindow", "Deck"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
